import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ChevronLeft, ChevronRight, Flame, MapPin, RefreshCw, Star, TrendingUp, Zap } from 'lucide-react'
import { dailyBriefing, restaurants } from '../data/mockData'

const insightConfig = {
  hot: { icon: Flame, color: 'text-orange-600', bg: 'bg-orange-50', border: 'border-orange-100', label: 'HOT LEAD' },
  opportunity: { icon: TrendingUp, color: 'text-rita-forest', bg: 'bg-rita-forest/5', border: 'border-rita-forest/10', label: 'OPPORTUNITY' },
  alert: { icon: Zap, color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-100', label: 'ACTION NEEDED' },
  new: { icon: Star, color: 'text-blue-600', bg: 'bg-blue-50', border: 'border-blue-100', label: 'NEW OPENING' },
  expansion: { icon: MapPin, color: 'text-violet-600', bg: 'bg-violet-50', border: 'border-violet-100', label: 'EXPANSION ALERT' },
}

const stagger = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.08 } }
}
const fadeUp = {
  hidden: { opacity: 0, y: 16 },
  show: { opacity: 1, y: 0, transition: { duration: 0.4, ease: [0.4, 0, 0.2, 1] } }
}

export default function DailyBriefing() {
  const navigate = useNavigate()
  const { date, weather, route, insights } = dailyBriefing

  return (
    <div className="bg-rita-ivory min-h-screen">
      {/* Header */}
      <div className="card-forest rounded-none pt-14 pb-6 px-5" style={{ borderRadius: '0 0 32px 32px' }}>
        <div className="flex items-center gap-3 mb-4">
          <button onClick={() => navigate('/home')} className="w-8 h-8 rounded-xl bg-white/10 flex items-center justify-center">
            <ChevronLeft size={18} className="text-white" />
          </button>
          <div>
            <p className="text-white/50 text-xs">{date}</p>
            <h1 className="text-white text-xl font-bold">AI Morning Briefing</h1>
          </div>
          <button className="ml-auto w-8 h-8 rounded-xl bg-white/10 flex items-center justify-center">
            <RefreshCw size={14} className="text-white/60" />
          </button>
        </div>

        {/* Route overview row */}
        <div className="flex gap-3 overflow-x-auto pb-1 scrollbar-hide">
          {[
            { label: 'Stops', value: route.stops.toString() },
            { label: 'Miles', value: route.miles.toString() },
            { label: 'Drive Time', value: route.driveTime },
            { label: 'Weather', value: `${weather.temp}° ${weather.condition}` },
          ].map(({ label, value }) => (
            <div key={label} className="bg-white/10 rounded-2xl px-4 py-2.5 flex-shrink-0 text-center">
              <p className="text-white/40 text-[9px] uppercase tracking-widest font-semibold">{label}</p>
              <p className="text-white text-sm font-bold mt-0.5">{value}</p>
            </div>
          ))}
        </div>
      </div>

      <motion.div className="px-4 pt-5 space-y-3" variants={stagger} initial="hidden" animate="show">
        <motion.div variants={fadeUp}>
          <p className="text-rita-muted text-xs font-semibold uppercase tracking-wider mb-3">
            {insights.length} insights generated by Rita AI
          </p>
        </motion.div>

        {insights.map((insight, i) => {
          const cfg = insightConfig[insight.type as keyof typeof insightConfig]
          const Icon = cfg.icon
          const restaurant = insight.restaurantId ? restaurants.find(r => r.id === insight.restaurantId) : null

          return (
            <motion.div key={i} variants={fadeUp}>
              <div className={`card-premium p-4 border ${cfg.border}`}>
                {/* Type label */}
                <div className="flex items-center justify-between mb-3">
                  <div className={`flex items-center gap-1.5 ${cfg.bg} ${cfg.color} rounded-full px-2.5 py-1`}>
                    <Icon size={11} />
                    <span className="text-[10px] font-black tracking-widest">{cfg.label}</span>
                  </div>
                  {restaurant && (
                    <span className="text-rita-muted text-[10px]">{restaurant.neighborhood}</span>
                  )}
                </div>

                <h3 className="text-rita-black font-bold text-base leading-snug mb-1.5">
                  {insight.title}
                </h3>
                <p className="text-rita-slate text-sm leading-relaxed">
                  {insight.body}
                </p>

                {restaurant && (
                  <div className="flex items-center gap-3 mt-3 pt-3 border-t border-rita-ivory-dark">
                    <div className="flex items-center gap-1.5 text-rita-muted text-xs">
                      <Star size={10} className="fill-rita-gold text-rita-gold" />
                      <span>{restaurant.rating}</span>
                    </div>
                    <span className="text-rita-ivory-mid">·</span>
                    <span className="text-rita-muted text-xs">{restaurant.cuisine}</span>
                    <span className="text-rita-ivory-mid">·</span>
                    <span className="text-rita-muted text-xs">{restaurant.distance}</span>
                  </div>
                )}

                <button
                  onClick={() => restaurant && navigate(`/accounts/${restaurant.id}`)}
                  className="mt-3 w-full flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-rita-forest text-white text-xs font-bold tracking-wide btn-press transition-premium"
                >
                  {insight.action}
                  <ChevronRight size={13} />
                </button>
              </div>
            </motion.div>
          )
        })}

        {/* Nearby suggestions */}
        <motion.div variants={fadeUp}>
          <h2 className="text-rita-black text-sm font-bold uppercase tracking-wider mt-2 mb-3">Suggested Prospects Nearby</h2>
          <div className="space-y-2">
            {[
              { name: "Goldie's Brunch Bar", reason: 'No loyalty program · 4.7★ · 0.3 mi', fit: '94% match' },
              { name: 'The Perch Rooftop', reason: 'Just opened · hiring 8 staff · 0.5 mi', fit: '91% match' },
              { name: 'Cactus Rose', reason: 'New opening 6 weeks ago · 0.9 mi', fit: '87% match' },
            ].map((item) => (
              <div key={item.name} className="card-premium p-3.5 flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-rita-forest/8 flex items-center justify-center flex-shrink-0">
                  <MapPin size={16} className="text-rita-forest" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-rita-black text-sm font-semibold">{item.name}</p>
                  <p className="text-rita-muted text-xs mt-0.5">{item.reason}</p>
                </div>
                <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full flex-shrink-0">
                  {item.fit}
                </span>
              </div>
            ))}
          </div>
        </motion.div>

        <div className="h-4" />
      </motion.div>
    </div>
  )
}
